kind: Service
apiVersion: v1
metadata:
  name: helloserver-service
spec:
  selector:
    app: goapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-helloserver
  labels:
    app: goapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: helloserver
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: go-ingress
    annotations:
      allow.http: "false"
  spec:
    rules:
    - host: go.rancher.huhsp.org.br
      http:
        paths:
          - path: /
            backend:
              serviceName: go-service
              servicePort: 80
